# Generated by Django 3.1.6 on 2021-02-26 03:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('product_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('max_licenses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('org_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=100)),
                ('org_type', models.CharField(choices=[('customer', 'Customer'), ('partner', 'Partner')], max_length=8)),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\+?1?\\d+$', '+##########')])),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'User')], default='user', max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 2, 26, 3, 28, 16, 254582, tzinfo=utc))),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=7)),
                ('orgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license_pgrm.organizations')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.datetime(2021, 2, 25, 22, 28, 16, 258578))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license_pgrm.userprofile', to_field='email')),
                ('orgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license_pgrm.organizations')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license_pgrm.entitlement')),
            ],
        ),
        migrations.AddField(
            model_name='entitlement',
            name='orgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license_pgrm.organizations'),
        ),
    ]
